### ISSUE TITLE
The call to pthread_mutex_unlock must be placed after pthread_cond_signal, not before it.

### ISSUE THREAD

**Issue by maskimthedog** [gkos/pq#1]
The call to pthread_mutex_unlock must be placed after pthread_cond_signal, not before it.

static inline int pq_put_head(pq_head *h, pqn *n)
{
	pthread_mutex_lock(&h->lock);
	pqn_unlink(n); /* I think I'm paranoid */
	if (pq_isempty(h)) {
		h->first = h->last = n;
	} else {
		n->next = h->first;
		h->first->prev = n;
		h->first = n;
	}
	h->size++;
	pthread_cond_signal(&h->cond);
	pthread_mutex_unlock(&h->lock);
	return 0;
}

**Comment by dhilst** [comment]
Sorry I didn't see this. Wouldn't this make it possible to the lock to be reacquired by another thread before the cond is signaled?

**Comment by maskimthedog** [comment]
No, not at all.

Check this out:
https://gist.github.com/rtv/4989304

**Comment by dhilst** [comment]
Now I understand, the code you pasted is right and the master is wrong. Do you want to create a PR for this? I would merge it :)

**Comment by dhilst** [comment]
Fixed by f44018e1a2c97911fbeb05f88fcc6813c0b27c74 thanks @maskimthedog, for reporting 
:)
